language: generic

services:
  - docker

branches:
  only:
    - master
    - develop
    - master-server
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=foretold-app/foretold
    - DOCKER_COMPOSE_VERSION=1.8.1
    - COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml

before_script:
  - echo Before-Script-OK

install:
  - docker-compose ps
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec app yarn server/db:create
  - docker-compose exec app yarn server/db:migrate
  - docker-compose restart app
  - docker-compose ps

script:
  - printenv
  - docker-compose exec app yarn guesstimator/test:ci
  - docker-compose exec app yarn cdf/test:ci
  - docker-compose exec app yarn bots/test:ci
  - docker-compose exec app yarn prediction-analysis/test:ci
  - docker-compose exec app yarn tests/test:ci
  - docker-compose exec app yarn packages/lint
